"""Add budgeted AutoDL Pro resources

Revision ID: a2c5e94d320b
Revises: f1d4b83c219a
Create Date: 2026-10-05 16:55:29.472382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c5e94d320b'
down_revision = 'f1d4b83c219a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('image_uuid', sa.String(length=160), nullable=False),
    sa.Column('gpu_spec_uuid', sa.String(length=80), nullable=False),
    sa.Column('gpu_label', sa.String(length=120), nullable=False),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('hourly_price_millis', sa.Integer(), nullable=False),
    sa.Column('cuda_v_from', sa.Integer(), nullable=False),
    sa.Column('data_centers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('compute_worker_heartbeats',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compute_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_gpu_seconds', sa.BigInteger(), nullable=False),
    sa.Column('max_cost_millis', sa.BigInteger(), nullable=True),
    sa.Column('gpu_seconds_used', sa.BigInteger(), nullable=False),
    sa.Column('cost_used_millis', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['compute_providers.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'problem_id', name='uq_compute_grant_team_problem')
    )
    with op.batch_alter_table('compute_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compute_grants_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compute_grants_team_id'), ['team_id'], unique=False)

    op.create_table('compute_policies',
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id')
    )
    op.create_table('compute_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grant_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('remote_id', sa.String(length=160), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['compute_grants.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['compute_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grant_id'),
    sa.UniqueConstraint('remote_id')
    )
    op.create_table('compute_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grant_id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('rate_millis', sa.Integer(), nullable=False),
    sa.Column('reserved_gpu_seconds', sa.BigInteger(), nullable=False),
    sa.Column('reserved_cost_millis', sa.BigInteger(), nullable=False),
    sa.Column('charged_gpu_seconds', sa.BigInteger(), nullable=True),
    sa.Column('charged_cost_millis', sa.BigInteger(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_requested', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('lease_owner', sa.String(length=80), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['compute_grants.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['compute_instances.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grant_id', 'request_id', name='uq_compute_session_request')
    )
    with op.batch_alter_table('compute_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compute_sessions_grant_id'), ['grant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compute_sessions_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    for table in ('compute_providers', 'compute_policies', 'compute_grants', 'compute_instances', 'compute_sessions'):
        if op.get_bind().execute(sa.text('SELECT 1 FROM ' + table + ' LIMIT 1')).first():
            raise RuntimeError('Cannot remove AutoDL allocations, credentials or billing history; archive them before downgrade.')
    with op.batch_alter_table('compute_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compute_sessions_state'))
        batch_op.drop_index(batch_op.f('ix_compute_sessions_grant_id'))

    op.drop_table('compute_sessions')
    op.drop_table('compute_instances')
    op.drop_table('compute_policies')
    with op.batch_alter_table('compute_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compute_grants_team_id'))
        batch_op.drop_index(batch_op.f('ix_compute_grants_problem_id'))

    op.drop_table('compute_grants')
    op.drop_table('compute_worker_heartbeats')
    op.drop_table('compute_providers')
    # ### end Alembic commands ###
