"""Add competition AI gateway

Revision ID: d8a2f19c630e
Revises: c7e284a15f90
Create Date: 2026-10-05 15:31:22.870331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a2f19c630e'
down_revision = 'c7e284a15f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('protocol', sa.String(length=24), nullable=False),
    sa.Column('secrets', sa.Text(), nullable=False),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('disabled_models', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('input_price', sa.Float(), nullable=False),
    sa.Column('output_price', sa.Float(), nullable=False),
    sa.Column('last_test', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_models', sa.JSON(), nullable=False),
    sa.Column('allowed_channels', sa.JSON(), nullable=False),
    sa.Column('max_calls', sa.Integer(), nullable=False),
    sa.Column('max_tokens', sa.BigInteger(), nullable=False),
    sa.Column('max_cost_micros', sa.BigInteger(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('calls_used', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.BigInteger(), nullable=False),
    sa.Column('cost_used_micros', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    with op.batch_alter_table('ai_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_grants_team_id'), ['team_id'], unique=False)

    op.create_table('ai_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['ai_grants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('ai_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_keys_grant_id'), ['grant_id'], unique=False)

    op.create_table('ai_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grant_id', sa.String(length=36), nullable=False),
    sa.Column('key_id', sa.String(length=36), nullable=True),
    sa.Column('evaluation_run_id', sa.String(length=36), nullable=True),
    sa.Column('channel_id', sa.String(length=36), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('endpoint', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cached_tokens', sa.BigInteger(), nullable=True),
    sa.Column('charged_tokens', sa.BigInteger(), nullable=False),
    sa.Column('charged_cost_micros', sa.BigInteger(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('first_token_ms', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['ai_channels.id'], ),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['ai_grants.id'], ),
    sa.ForeignKeyConstraint(['key_id'], ['ai_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_evaluation_run_id'), ['evaluation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_grant_id'), ['grant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_key_id'), ['key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_status'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_model'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_key_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_grant_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_evaluation_run_id'))

    op.drop_table('ai_usage')
    with op.batch_alter_table('ai_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_keys_grant_id'))

    op.drop_table('ai_keys')
    with op.batch_alter_table('ai_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_grants_team_id'))

    op.drop_table('ai_grants')
    op.drop_table('ai_channels')
    # ### end Alembic commands ###
